version: '3'
services:
  code-server:
    image: 'lscr.io/linuxserver/code-server:latest'
    container_name: code-server
    hostname: code-server
    network_mode: host
    environment:
      - SERVICE_FQDN_CODESERVER_8443
      - PUID=1000
      - PGID=1000
      - TZ=America/Santo_Domingo
      - PASSWORD=${SERVICE_PASSWORD_64_PASSWORDCODESERVER}
      - SUDO_PASSWORD=${SERVICE_PASSWORD_SUDOCODESERVER}
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - /data/code-server/config:/config
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8443'
      interval: 2s
      timeout: 10s
      retries: 15
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.http-0-code-server.rule=Host(`code.nikasol.xyz`) && PathPrefix(`/`)'
      - traefik.http.routers.http-0-code-server.entryPoints=http
      # enable https
      - traefik.http.routers.http-0-code-server.middlewares=gzip
      - traefik.http.services.http-0-code-server.loadbalancer.server.port=8090
      - traefik.http.routers.http-0-code-server.tls=true
      - traefik.http.routers.http-0-code-server.tls.certresolver=letsencrypt
      - traefik.http.routers.http-0-code-server.entryPoints=https
      - traefik.http.routers.http-0-code-server.middlewares=redirect-to-https

# configs
# domain: https://code.nikasol.xyz:8443
# domain: https://code.nikasol.xyz:8443,https://run-code.nikasol.xyz:11010
