version: '3'
services:
  web:
    image: ghcr.io/cabaalexander/coolify-nginx-reverse-proxy:latest
    container_name: nginx-proxy-${W_APP:-moonlight}
    environment:
      - W_PROXY_URL=${W_PROXY_URL:-https://coolify.io}
      - W_CLIENT_MAX_BODY_SIZE=${W_CLIENT_MAX_BODY_SIZE:-20M}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.http-0-${W_APP:-moonlight}.rule=Host(`${W_APP:-moonlight}.${W_DOMAIN:-example.com}`) && PathPrefix(`/`)'
      - traefik.http.routers.http-0-${W_APP:-moonlight}.entryPoints=http
      # enable https
      - traefik.http.routers.http-0-${W_APP:-moonlight}.middlewares=gzip
      - traefik.http.services.http-0-${W_APP:-moonlight}.loadbalancer.server.port=8090
      - traefik.http.routers.http-0-${W_APP:-moonlight}.tls=true
      - traefik.http.routers.http-0-${W_APP:-moonlight}.tls.certresolver=letsencrypt
      - traefik.http.routers.http-0-${W_APP:-moonlight}.entryPoints=https
      - traefik.http.routers.http-0-${W_APP:-moonlight}.middlewares=redirect-to-https

# configs
# domain: https://moonlight.nikasol.xyz:80

