version: "3.8"
services:
  dashy:
    image: lissy93/dashy
    container_name: dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - /data/dashy/conf.yml:/app/public/conf.yml # @see: create volume beforehand
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.http-0-dashy.rule=Host(`dashy.10.0.0.37.sslip.io`) && PathPrefix(`/`)'
      - traefik.http.routers.http-0-dashy.entryPoints=http
      # enable https
      - traefik.http.routers.http-0-dashy.middlewares=gzip
      - traefik.http.services.http-0-dashy.loadbalancer.server.port=80
      - traefik.http.routers.http-0-dashy.tls=true
      - traefik.http.routers.http-0-dashy.tls.certresolver=letsencrypt
      - traefik.http.routers.http-0-dashy.entryPoints=https
      - traefik.http.routers.http-0-dashy.middlewares=redirect-to-https

# configs
# domain: https://dashy.nikasol.xyz:80
