version: '3'
services:
  moonlight:
    image: ghcr.io/cabaalexander/coolify-nginx-reverse-proxy:latest
    container_name: nginx-proxy-moonlight
    hostname: nginx-proxy-moonlight
    environment:
      - W_PROXY_URL=${W_PROXY_URL:-https://coolify.io}
      - W_CLIENT_MAX_BODY_SIZE=${W_CLIENT_MAX_BODY_SIZE:-20M}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.http-0-moonlight.rule=Host(`moonlight.nikasol.xyz`) && PathPrefix(`/`)'
      - traefik.http.routers.http-0-moonlight.entryPoints=http
      # enable https
      - traefik.http.routers.http-0-moonlight.middlewares=gzip
      - traefik.http.services.http-0-moonlight.loadbalancer.server.port=8090
      - traefik.http.routers.http-0-moonlight.tls=true
      - traefik.http.routers.http-0-moonlight.tls.certresolver=letsencrypt
      - traefik.http.routers.http-0-moonlight.entryPoints=https
      - traefik.http.routers.http-0-moonlight.middlewares=redirect-to-https

# configs
# domain: https://moonlight.nikasol.xyz:80

