version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
    environment:
      TZ: 'America/Santo_Domingo'
      WEBPASSWORD: ${W_PASSWORD}
    # Volumes store your data between container upgrades
    volumes:
      - /data/pihole/etc-pihole:/etc/pihole
      - /data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.http-0-pihole.rule=Host(`pihole.10.0.0.37.sslip.io`) && PathPrefix(`/`)'
      - traefik.http.routers.http-0-pihole.entryPoints=http

# configs
# domain: http://pihole.10.0.0.37.sslip.io:80
